version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatgpt_products
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - appnet

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/chatgpt_products
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:



